### ISSUE TITLE
LA生成的指令高、低错位。

### ISSUE THREAD

**Issue by All-less** [DreaminginCodeZH/mipsasm#5]

**Comment by zhanghai** [comment]
请提供更多详情，例如：
- 出错的示例
- 错误行为
- 预期行为

**Comment by All-less** [comment]
例如对于以下代码：

```
    add $0, $0, $0
label:
    add $0, $0, $0
    la $1, label
```

汇编后生成3.bin，内容如下：

```
0000 0020 0000 0020 3c01 0004 3421 0000
```

再进行反汇编后得到：

```
add $zero, $zero, $zero
add $zero, $zero, $zero
lui $at, 4
ori $at, $at, 0
```

显然`$1`寄存器中的结果为`0x00040000`，但正确地址应为`0x00000004`。

关于版本：我用的是施老师FTP上提供的版本，不确定目前的版本是否正确。

**Comment by zhanghai** [comment]
是版本问题。我在当时进行过大量错误修复，FTP 上的版本可能过老。

0b49861 修复了这个问题，在 v1.0.2 中已经包含了这个 commit。

我的反汇编输出：

``` asm
add $zero, $zero, $zero
add $zero, $zero, $zero
lui $at, 0
ori $at, $at, 4
```

请通知大家从https://github.com/DreaminginCodeZH/mipsasm/releases 下载，以及 FTP 上的旧版本可以下线/更新一下。
